# Generated by Django 4.2.14 on 2024-10-23 16:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('buddy_groups', '0001_initial'),
        ('buddy_profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupmembers',
            name='buddy_profile_member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='buddy_profiles.buddyprofile'),
        ),
        migrations.AddField(
            model_name='groupmembers',
            name='group_belong_to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='buddy_groups.buddygroup'),
        ),
        migrations.AddField(
            model_name='groupadmins',
            name='buddy_profile_admin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='buddy_profiles.buddyprofile'),
        ),
        migrations.AddField(
            model_name='groupadmins',
            name='group_belong_to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='buddy_groups.buddygroup'),
        ),
        migrations.AddField(
            model_name='buddygroup',
            name='group_admins',
            field=models.ManyToManyField(related_name='group_admins', through='buddy_groups.GroupAdmins', to='buddy_profiles.buddyprofile'),
        ),
        migrations.AddField(
            model_name='buddygroup',
            name='group_members',
            field=models.ManyToManyField(related_name='group_members', through='buddy_groups.GroupMembers', to='buddy_profiles.buddyprofile'),
        ),
    ]
