# Generated by Django 4.2.14 on 2024-10-23 16:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('buddy_groups', '0001_initial'),
        ('buddy_expenses', '0001_initial'),
        ('buddy_profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='settlementbyparticipants',
            name='who_settle_simple_payment_up',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='buddy_profiles.buddyprofile'),
        ),
        migrations.AddField(
            model_name='paymentsmadeitbypayers',
            name='what_expense_belong_to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='buddy_expenses.buddyexpense'),
        ),
        migrations.AddField(
            model_name='paymentsmadeitbypayers',
            name='who_do_simple_payment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='buddy_profiles.buddyprofile'),
        ),
        migrations.AddField(
            model_name='participantsofexpensepayment',
            name='expense',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='buddy_expenses.buddyexpense'),
        ),
        migrations.AddField(
            model_name='participantsofexpensepayment',
            name='participant_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='buddy_profiles.buddyprofile'),
        ),
        migrations.AddField(
            model_name='buddyexpense',
            name='buddy_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='buddy_groups.buddygroup', verbose_name='Buddy group'),
        ),
        migrations.AddField(
            model_name='buddyexpense',
            name='participants_of_expense_payment',
            field=models.ManyToManyField(related_name='participants_of_expense_payment', through='buddy_expenses.ParticipantsOfExpensePayment', to='buddy_profiles.buddyprofile'),
        ),
        migrations.AddField(
            model_name='buddyexpense',
            name='payments_made_it_by_payers',
            field=models.ManyToManyField(related_name='payments_made_it_by_payers', through='buddy_expenses.PaymentsMadeItByPayers', to='buddy_profiles.buddyprofile'),
        ),
        migrations.AddField(
            model_name='buddyexpense',
            name='settlement_by_participants',
            field=models.ManyToManyField(related_name='settlement_by_participants', through='buddy_expenses.SettlementByParticipants', to='buddy_profiles.buddyprofile'),
        ),
    ]
